# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f2dfe3c1a9596d19fc456b55ae76e452122c94d52cc4e2c14e69f77801815bd038cf85fc582d925664223881e0e5c53324c7357677fab65708ca13fe9368f4d

test:
  secret_key_base: cf04e93ad063f1bed9fe3b5630e7d292cdac3291a41656fc33d098f81610a5c792225365164cf41796ec7c5b23a4026faa775080d424e89dd052a47a5008c49e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
